fastlane_version "2.212.1"

default_platform :ios

platform :ios do
    desc 'Run Tests'
    lane :tests do
       scan(
            scheme: "CICDTest",
            devices: ["iPhone 12"]
        )
    end
end