name: Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Install Bundler
        run: gem install bundler
        
      - name: Install gems
        run: bundle install

      - name: Setup - Ruby and bundler dependencies
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Test - Fastlane tests
        run: bundle exec fastlane tests


